# Generated by Django 4.2.4 on 2023-08-09 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_serviceuser_is_mechanic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('car_model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
