# Generated by Django 4.2.4 on 2023-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cars_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='description',
            new_name='problem_description',
        ),
    ]
