# Generated by Django 4.2.4 on 2023-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_description_cars_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='cars_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
