# Generated by Django 4.2.4 on 2023-08-09 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_cars_working_mechanic_alter_cars_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='working_mechanic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cars_serviced', to=settings.AUTH_USER_MODEL),
        ),
    ]
