# Generated by Django 4.2.4 on 2023-08-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_cars_working_mechanic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='working_mechanic',
        ),
    ]
