# Generated by Django 4.2.4 on 2023-08-11 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_cars_working_mechanic_cars_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886, message='No cars existed before the year 1886!!!'), django.core.validators.MaxValueValidator(2024, message='Car has not been made yet!')]),
        ),
    ]
