# Generated by Django 4.2.4 on 2023-08-11 15:52

import django.core.validators
from django.db import migrations, models
import mechanic_project_v2.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_cars_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_model',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1, message='Manufacturer name cannot be less than 1 symbols!'), django.core.validators.MaxLengthValidator(30, message='Manufacturer name cannot be more than 30 symbols!')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='manufacturer',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1, message='Manufacturer name cannot be less than 1 symbols!'), django.core.validators.MaxLengthValidator(30, message='Manufacturer name cannot be more than 30 symbols!')]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886, message='No cars existed before the year 1886!!!'), django.core.validators.MaxValueValidator(2024, message='Car has not been made yet! Enter valid year!')]),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Name cannot be less than 2 symbols!'), django.core.validators.MaxLengthValidator(30, message='Name cannot be more than 30 symbols!'), mechanic_project_v2.web.validators.validate_only_letters_in_name]),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Name cannot be less than 2 symbols!'), django.core.validators.MaxLengthValidator(30, message='Name cannot be more than 30 symbols!'), mechanic_project_v2.web.validators.validate_only_letters_in_name]),
        ),
    ]
