# Generated by Django 4.2.4 on 2023-08-11 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_cars_car_model_alter_cars_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(16, message='Invalid VIN! VIN number has 17 symbols!'), django.core.validators.MaxValueValidator(18, message='Invalid VIN! VIN number has 17 symbols!')]),
        ),
    ]
