# Generated by Django 4.2.4 on 2023-08-11 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_cars_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(16, message='Invalid VIN! VIN number has 17 symbols!'), django.core.validators.MaxLengthValidator(17, message='Invalid VIN! VIN number has 17 symbols!')]),
        ),
    ]
